version: "3.9"
services:

      mysql:
        container_name: mysql
        image: mysql:latest
        ports:
          - "3308:3306"
        environment:
          MYSQL_ROOT_PASSWORD: M354224331315m
          MYSQL_USER: crm
          MYSQL_PASSWORD: crm
          MYSQL_DATABASE: crmdatabase
        volumes:
          - ./mysql-data:/var/lib/mysql
        command: mysqld --skip-name-resolve=0
        networks:
          - crm-network
        restart: always
        
      backend:
        container_name: Customer-Relationship-Management-0.0.2-SNAPSHOT
        build: .
        ports:
          - "8443:8443"
        depends_on:
          - mysql
        networks:
          - crm-network
        environment:
          - MYSQL_HOST=mysql
          - MYSQL_USERNAME=crm
          - MYSQL_PASSWORD=crm
          - MYSQL_DATABASE=crmdatabase
          - MYSQL_PORT=3306
        command: ["java", "-jar", "/app/backend/build/libs/Customer-Relationship-Management-0.0.2-SNAPSHOT.jar"]
        volumes:
          - .:/app
          - gradle-cache:/home/gradle/.gradle


networks:
  crm-network:
    driver: bridge
volumes:
  gradle-cache: