version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: M354224331315m
      MYSQL_USER: crm
      MYSQL_PASSWORD: crm
      MYSQL_DATABASE: crmdatabase
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: mysqld --skip-name-resolve=0
    networks:
      - crm-network
    restart: always

networks:
  crm-network:
    driver: bridge